apiVersion: v1
kind: Secret
metadata:
  name: sonarr-exporter-secret
type: Opaque
stringData:
  config.json: |-
    {
      "apiKey": "YOURAPIKEYHERE",
      "sonarrUrl": "http://sonarr:8989/api"
    }
